name: Build and Release Go Project

on:
  push:
    tags:
      - 'v*'  # Only triggers on version tags like v1.2.3

jobs:
  build:
    name: Build Cross-Platform Binaries
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goos: darwin
            goarch: arm64  # remove if you want to include macOS M1 builds

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Set up environment
        run: echo "RELEASE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build binary
        run: |
          mkdir -p dist
          EXT=""
          if [ "${{ matrix.goos }}" = "windows" ]; then EXT=".exe"; fi
          cd cmd/cli
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o ../../dist/papermctui-${{ matrix.goos }}-${{ matrix.goarch }}$EXT .

      - name: Upload binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: binaries-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/

  release:
    name: Create GitHub Release with Binaries
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download all built binaries
        uses: actions/download-artifact@v4
        with:
          path: dist/

      - name: Flatten binaries into dist/
        run: |
          find dist/ -type f -exec mv {} dist/ \;

      - name: Extract tag
        run: echo "RELEASE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Create GitHub Release with binaries
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          name: Release ${{ env.RELEASE_TAG }}
          body: |
            Cross-platform binaries built automatically.
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
